In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("C:/Users/soumy/OneDrive/Documents/abc(1).csv",low_memory=False)
data

,Registrar,Enrolment Agency,State,District,Sub District,Pin Code,Gender,Age,Aadhaar generated,Enrolment Rejected,Residents providing email,Residents providing mobile number
0,Allahabad Bank,A-Onerealtors Pvt Ltd,Uttar Pradesh,Allahabad,Meja,212303,F,7,1,0,0,1
1,Allahabad Bank,Asha Security Guard Services,Uttar Pradesh,Sonbhadra,Robertsganj,231213,M,8,1,0,0,0
2,Allahabad Bank,SGS INDIA PVT LTD,Uttar Pradesh,Sultanpur,Sultanpur,227812,F,13,1,0,0,1
3,Allahabad Bank,Sri Ramraja Sarkar Lok Kalyan Trust,Uttar Pradesh,Shamli,Shamli,247775,M,6,1,0,0,1
4,Allahabad Bank,Transmoovers India,Uttar Pradesh,Gorakhpur,Sahjanwa,273001,M,8,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
440813,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Palamu,Patan,822123,M,1,3,0,0,1
440814,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Palamu,Patan,822123,M,2,1,0,0,1
440815,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Palamu,Patan,822123,M,3,3,0,0,1
440816,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Palamu,Patan,822123,M,4,1,0,0,0
440817,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Ranchi,Ranchi,834002,F,3,1,0,0,1

In [3]:
data.drop_duplicates()

,Registrar,Enrolment Agency,State,District,Sub District,Pin Code,Gender,Age,Aadhaar generated,Enrolment Rejected,Residents providing email,Residents providing mobile number
0,Allahabad Bank,A-Onerealtors Pvt Ltd,Uttar Pradesh,Allahabad,Meja,212303,F,7,1,0,0,1
1,Allahabad Bank,Asha Security Guard Services,Uttar Pradesh,Sonbhadra,Robertsganj,231213,M,8,1,0,0,0
2,Allahabad Bank,SGS INDIA PVT LTD,Uttar Pradesh,Sultanpur,Sultanpur,227812,F,13,1,0,0,1
3,Allahabad Bank,Sri Ramraja Sarkar Lok Kalyan Trust,Uttar Pradesh,Shamli,Shamli,247775,M,6,1,0,0,1
4,Allahabad Bank,Transmoovers India,Uttar Pradesh,Gorakhpur,Sahjanwa,273001,M,8,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
440813,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Palamu,Patan,822123,M,1,3,0,0,1
440814,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Palamu,Patan,822123,M,2,1,0,0,1
440815,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Palamu,Patan,822123,M,3,3,0,0,1
440816,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Palamu,Patan,822123,M,4,1,0,0,0
440817,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Ranchi,Ranchi,834002,F,3,1,0,0,1

In [4]:
data.dropna()

,Registrar,Enrolment Agency,State,District,Sub District,Pin Code,Gender,Age,Aadhaar generated,Enrolment Rejected,Residents providing email,Residents providing mobile number
0,Allahabad Bank,A-Onerealtors Pvt Ltd,Uttar Pradesh,Allahabad,Meja,212303,F,7,1,0,0,1
1,Allahabad Bank,Asha Security Guard Services,Uttar Pradesh,Sonbhadra,Robertsganj,231213,M,8,1,0,0,0
2,Allahabad Bank,SGS INDIA PVT LTD,Uttar Pradesh,Sultanpur,Sultanpur,227812,F,13,1,0,0,1
3,Allahabad Bank,Sri Ramraja Sarkar Lok Kalyan Trust,Uttar Pradesh,Shamli,Shamli,247775,M,6,1,0,0,1
4,Allahabad Bank,Transmoovers India,Uttar Pradesh,Gorakhpur,Sahjanwa,273001,M,8,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
440813,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Palamu,Patan,822123,M,1,3,0,0,1
440814,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Palamu,Patan,822123,M,2,1,0,0,1
440815,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Palamu,Patan,822123,M,3,3,0,0,1
440816,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Palamu,Patan,822123,M,4,1,0,0,0
440817,Women and Child Development Govt. of Jharkhand,Women and Child Development,Jharkhand,Ranchi,Ranchi,834002,F,3,1,0,0,1

In [5]:
data.columns

Index(['Registrar', 'Enrolment Agency', 'State', 'District', 'Sub District',
       'Pin Code', 'Gender', 'Age', 'Aadhaar generated', 'Enrolment Rejected',
       'Residents providing email', 'Residents providing mobile number'],
      dtype='object')

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440818 entries, 0 to 440817
Data columns (total 12 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Registrar                          440818 non-null  object
 1   Enrolment Agency                   440818 non-null  object
 2   State                              440818 non-null  object
 3   District                           440818 non-null  object
 4   Sub District                       440818 non-null  object
 5   Pin Code                           440818 non-null  object
 6   Gender                             440818 non-null  object
 7   Age                                440818 non-null  int64
 8   Aadhaar generated                  440818 non-null  int64
 9   Enrolment Rejected                 440818 non-null  int64
 10  Residents providing email          440818 non-null  int64
 11  Residents providing mobile number  440818 non-null  int64
dtypes: int64(5), object(7)
memory usage: 40.4+ MB

In [7]:
# 1. Find out the total number of cards approved by States.

In [8]:
data.groupby('State')['Aadhaar generated'].sum()

State
Andaman and Nicobar Islands         5
Andhra Pradesh                   5798
Arunachal Pradesh                 913
Assam                            3213
Bihar                          162607
Chandigarh                        259
Chhattisgarh                     6604
Dadra and Nagar Haveli            140
Daman and Diu                     105
Delhi                            8426
Goa                              1167
Gujarat                         34844
Haryana                          6804
Himachal Pradesh                 1547
Jammu and Kashmir                1234
Jharkhand                        9868
Karnataka                       19764
Kerala                          15143
Lakshadweep                         4
Madhya Pradesh                  53276
Maharashtra                     26085
Manipur                          1323
Meghalaya                         277
Mizoram                          6279
Nagaland                          545
Odisha                          18182
Others                             12
Puducherry                         83
Punjab                           6506
Rajasthan                       39570
Sikkim                             50
Tamil Nadu                      32485
Telangana                        5018
Tripura                           908
Uttar Pradesh                  103767
Uttarakhand                     13227
West Bengal                    119901
Name: Aadhaar generated, dtype: int64

In [9]:
# 2. Find out the total number of cards Enrolment rejected by states.

In [10]:
data.groupby('State')['Enrolment Rejected'].sum()

State
Andaman and Nicobar Islands       2
Andhra Pradesh                  373
Arunachal Pradesh                79
Assam                            28
Bihar                          7209
Chandigarh                        9
Chhattisgarh                    380
Dadra and Nagar Haveli            3
Daman and Diu                     2
Delhi                           591
Goa                             127
Gujarat                        2500
Haryana                         532
Himachal Pradesh                123
Jammu and Kashmir               204
Jharkhand                       477
Karnataka                      1445
Kerala                          538
Lakshadweep                       1
Madhya Pradesh                 3509
Maharashtra                    1818
Manipur                         190
Meghalaya                         2
Mizoram                         185
Nagaland                         43
Odisha                         1596
Others                            0
Puducherry                       10
Punjab                          421
Rajasthan                      2035
Sikkim                            2
Tamil Nadu                     1193
Telangana                       274
Tripura                          62
Uttar Pradesh                  5286
Uttarakhand                     955
West Bengal                    6372
Name: Enrolment Rejected, dtype: int64

In [11]:
# 3. Find out the total number of cards approved by Districts.

In [13]:
data.groupby('District')['Aadhaar generated'].sum()

District
Adilabad         265
Agra            2283
Ahmadnagar       476
Ahmedabad       4212
Aizawl          1095
                ...
Wokha             32
Yadgir           325
Yamuna Nagar     197
Yavatmal         712
Zunheboto          8
Name: Aadhaar generated, Length: 664, dtype: int64

In [14]:
# 4. Find out the total number of cards rejected by Districts.

In [16]:
data.groupby('District')['Enrolment Rejected'].sum()

District
Adilabad          7
Agra            137
Ahmadnagar       45
Ahmedabad       278
Aizawl          111
               ...
Wokha             2
Yadgir           28
Yamuna Nagar     11
Yavatmal         78
Zunheboto         0
Name: Enrolment Rejected, Length: 664, dtype: int64

In [ ]:
# 5.Total Count Gender Based

In [23]:
data['Gender'].value_counts()

M    292798
F    148013
T         7
Name: Gender, dtype: int64

In [ ]:
# 6.Count Records age <25, age between 25 &35, age>45

In [28]:
data[data['Age']<25].count()

Registrar                            296836
Enrolment Agency                     296836
State                                296836
District                             296836
Sub District                         296836
Pin Code                             296836
Gender                               296836
Age                                  296836
Aadhaar generated                    296836
Enrolment Rejected                   296836
Residents providing email            296836
Residents providing mobile number    296836
dtype: int64

In [30]:
data[(data['Age']>=25)&(data['Age']<=35)].count()

Registrar                            62512
Enrolment Agency                     62512
State                                62512
District                             62512
Sub District                         62512
Pin Code                             62512
Gender                               62512
Age                                  62512
Aadhaar generated                    62512
Enrolment Rejected                   62512
Residents providing email            62512
Residents providing mobile number    62512
dtype: int64

In [31]:
data[data['Age']>45].count()

Registrar                            50610
Enrolment Agency                     50610
State                                50610
District                             50610
Sub District                         50610
Pin Code                             50610
Gender                               50610
Age                                  50610
Aadhaar generated                    50610
Enrolment Rejected                   50610
Residents providing email            50610
Residents providing mobile number    50610
dtype: int64